---
pve_update_system:     true
pve_configure_repos:   true
pve_configure_network: true
pve_configure_sdn:     true
pve_api_host:          "{{ ansible_host }}"
pve_sdn_primary_node:  "{{ ansible_play_hosts | first }}"
