---
# =============================================================================
# host_vars – pve-alpha-03
# =============================================================================

pve_node_ip:          "192.168.10.13"
pve_node_cidr_prefix: "24"
pve_node_gw:          "192.168.10.1"
pve_node_dns:         "192.168.10.1"
pve_cluster_link1_ip: ""
pve_cluster_primary:  false

pve_nic_aliases:
  - mac:   "aa:bb:cc:03:01:01"
    alias: "alpha03-mgmt-a"
    role:  "bond0"
  - mac:   "aa:bb:cc:03:01:02"
    alias: "alpha03-mgmt-b"
    role:  "bond0"
  - mac:   "aa:bb:cc:03:02:01"
    alias: "alpha03-stor-a"
    role:  "bond1"
  - mac:   "aa:bb:cc:03:02:02"
    alias: "alpha03-stor-b"
    role:  "bond1"
  - mac:   "aa:bb:cc:03:03:01"
    alias: "alpha03-vm-a"
    role:  "bond2"
  - mac:   "aa:bb:cc:03:03:02"
    alias: "alpha03-vm-b"
    role:  "bond2"

pve_bond1_enabled: true
pve_bond2_enabled: true

pve_storage_bridges:
  - iface:   "vmbr10"
    vlan_id: 10
    address: "10.10.10.13"
    netmask: "24"
    comment: "NFS Storage"
  - iface:   "vmbr11"
    vlan_id: 11
    address: "10.10.11.13"
    netmask: "24"
    comment: "iSCSI-1"
  - iface:   "vmbr12"
    vlan_id: 12
    address: "10.10.12.13"
    netmask: "24"
    comment: "iSCSI-2"
